name: flutter_social_media_with_clean_architecture
description: A Flutter project made with Clean Architecture.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.0
  go_router: ^10.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  uuid: ^4.0.0
  video_player: ^2.7.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
